import { Helmet } from "react-helmet";  // Import Helmet for managing the head

export default function MainHead({ title, description, image }) {
    return (
        <Helmet>
            <title>{title || "Create React App"}</title> {/* Set the document title */}
            <meta
                name="description"
                content={description || "Generated by create-react-app"} // Set the meta description
            />
            <link rel="icon" href={image || "/favicon.ico"} /> {/* Set the favicon */}
        </Helmet>
    );
}
